[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot
$manifestScript = Join-Path $PSScriptRoot "Generate-DocsManifest.ps1"
$buildScript = Join-Path $PSScriptRoot "Build-DocsSite.ps1"
$testScript = Join-Path $PSScriptRoot "Test-DocsSite.ps1"
$stagingDirectoryName = "_site"
$stagingRoot = Join-Path $repoRoot $stagingDirectoryName

if (-not (Test-Path -LiteralPath $manifestScript -PathType Leaf)) {
    throw "Manifest script not found: $manifestScript"
}
if (-not (Test-Path -LiteralPath $buildScript -PathType Leaf)) {
    throw "Build script not found: $buildScript"
}

& $manifestScript
& $buildScript -OutputDirectory $stagingDirectoryName

$branchFiles = @(
    "index.html",
    "styles.css",
    "site.js",
    "search-index.json",
    ".nojekyll"
)

foreach ($relativePath in $branchFiles) {
    $sourcePath = Join-Path $stagingRoot $relativePath
    $destinationPath = Join-Path $repoRoot $relativePath
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
        throw "Generated branch source file is missing: $relativePath"
    }
    Copy-Item -LiteralPath $sourcePath -Destination $destinationPath -Force
}

# Remove only pages previously generated by this publisher. Source Markdown,
# diagrams, and any user-authored HTML are left untouched.
$generatedMarker = "GENERATED_DOCUMENTATION_SITE"
Get-ChildItem -LiteralPath (Join-Path $repoRoot "docs") -Recurse -File -Filter "*.html" -ErrorAction SilentlyContinue |
    Where-Object { (Get-Content -LiteralPath $_.FullName -Raw) -match $generatedMarker } |
    Remove-Item -Force

$generatedPages = Get-ChildItem -LiteralPath (Join-Path $stagingRoot "docs") -Recurse -File -Filter "*.html"
foreach ($page in $generatedPages) {
    $relativePath = [System.IO.Path]::GetRelativePath((Join-Path $stagingRoot "docs"), $page.FullName)
    $destinationPath = Join-Path $repoRoot (Join-Path "docs" ($relativePath -replace '/', '\'))
    $destinationDirectory = Split-Path -Parent $destinationPath
    New-Item -ItemType Directory -Path $destinationDirectory -Force | Out-Null
    Copy-Item -LiteralPath $page.FullName -Destination $destinationPath -Force
}

& $testScript -OutputDirectory "."

Write-Host "Published the GitHub Pages branch source to the repository root."
